export const rows = [
  {
    id: 1,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Ha Noi',
    receiverName: 'Jon',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 35,
  },
  {
    id: 2,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Hai Phong',
    receiverName: 'Cersei',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 42,
  },
  {
    id: 3,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Ha Noi',
    receiverName: 'Jaime',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 45,
  },
  {
    id: 4,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Thai Nguyn',
    receiverName: 'Arya',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 16,
  },
  {
    id: 5,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Thanh Hoa',
    receiverName: 'Daenerys',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: null,
  },
  {
    id: 6,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Ha Noi',
    receiverName: null,
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 150,
  },
  {
    id: 7,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Ha Noi',
    receiverName: 'Ferrara',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 44,
  },
  {
    id: 8,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Cao Bang',
    receiverName: 'Rossini',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 36,
  },
  {
    id: 9,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Lang Son',
    receiverName: 'Harvey',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 65,
  },
  {
    id: 10,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Hai Phong',
    receiverName: 'Jon',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 35,
  },
  {
    id: 11,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Hai Phong',
    receiverName: 'Cersei',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 42,
  },
  {
    id: 12,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Dien Bien',
    receiverName: 'Jaime',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 45,
  },
  {
    id: 13,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Dien Bien',
    receiverName: 'Arya',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 16,
  },
  {
    id: 14,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Ha Noi',
    receiverName: 'Daenerys',
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: null,
  },
  {
    id: 15,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Nghe An',
    receiverName: null,
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 150,
  },
  {
    id: 16,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Thai Nguyn',
    receiverName: null,
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 150,
  },
  {
    id: 17,
    senderName: 'Nhut Le',
    senderPhone: '0123456789',
    senderAddress: 'Ha Noi',
    receiverName: null,
    receiverPhone: '9876543210',
    receiverAddress: 'Khum bic',
    from: 'abx',
    to: 'xyz',
    cost: 150,
  },
];
